/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ap.extraoefening1;

import java.time.Duration;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author maxim
 */
public class Gui extends javax.swing.JFrame {
    
    Collectie collectie;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        collectie = new Collectie("Naam collectie");
        Bestand bestand = new Film("Interstellar", 600000, Duration.ofHours(2));
        collectie.addBestand(bestand);
        buttonGroupBestandstype.add(jRadioButtonFilm);
        buttonGroupBestandstype.add(jRadioButtonFoto);
        buttonGroupBestandstype.add(jRadioButtonMuziek);
        jRadioButtonFoto.setSelected(true);
        jComboBoxGenre.setModel(new DefaultComboBoxModel(Genre.values()));
        setVisibility("foto");
        jCheckBoxHeeftGenre.setSelected(true);
    }
    
    private void updateLijst() {
        DefaultListModel defaultListModel = new DefaultListModel();
        for (Bestand bestand : collectie.getMuziek()) {
            defaultListModel.addElement(bestand);
        }
        jListBestanden.setModel(defaultListModel);
    }
    
    private void setVisibility(String type) {
        if ("film".equals(type)) {
            jPanelSpeelduur.setVisible(true);
            jPanelMuziek.setVisible(false);
            jPanelFoto.setVisible(false);
        } else if ("muziek".equals(type)) {
            jPanelSpeelduur.setVisible(true);
            jPanelMuziek.setVisible(true);
            jPanelFoto.setVisible(false);
        } else {
            jPanelSpeelduur.setVisible(false);
            jPanelMuziek.setVisible(false);
            jPanelFoto.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBestandstype = new javax.swing.ButtonGroup();
        jDialogMessage = new javax.swing.JDialog();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonFoto = new javax.swing.JRadioButton();
        jRadioButtonFilm = new javax.swing.JRadioButton();
        jRadioButtonMuziek = new javax.swing.JRadioButton();
        jTextFieldNaam = new javax.swing.JTextField();
        jLabelNaam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFoto = new javax.swing.JPanel();
        jLabelPixelsPerInch = new javax.swing.JLabel();
        jTextFieldPixelsPerInch = new javax.swing.JTextField();
        jPanelSpeelduur = new javax.swing.JPanel();
        jLabelSpeelduur = new javax.swing.JLabel();
        jTextFieldSpeelduur = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanelMuziek = new javax.swing.JPanel();
        jLabelNaamArtiest = new javax.swing.JLabel();
        jTextFieldNaamArtiest = new javax.swing.JTextField();
        jComboBoxGenre = new javax.swing.JComboBox<>();
        jCheckBoxHeeftGenre = new javax.swing.JCheckBox();
        jButtonToevoegen = new javax.swing.JButton();
        jTextFieldGrootte = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBestanden = new javax.swing.JList<>();
        jButtonSorteerOpNaam = new javax.swing.JButton();
        jButtonSorteerOpGrootte = new javax.swing.JButton();
        jButtonBewaringsdatum = new javax.swing.JButton();

        javax.swing.GroupLayout jDialogMessageLayout = new javax.swing.GroupLayout(jDialogMessage.getContentPane());
        jDialogMessage.getContentPane().setLayout(jDialogMessageLayout);
        jDialogMessageLayout.setHorizontalGroup(
            jDialogMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogMessageLayout.setVerticalGroup(
            jDialogMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonFoto.setText("Foto");
        jRadioButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFotoActionPerformed(evt);
            }
        });

        jRadioButtonFilm.setText("Film");
        jRadioButtonFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFilmActionPerformed(evt);
            }
        });

        jRadioButtonMuziek.setText("Muziek");
        jRadioButtonMuziek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMuziekActionPerformed(evt);
            }
        });

        jLabelNaam.setText("Naam");

        jLabel1.setText("Grootte in MB");

        jLabelPixelsPerInch.setText("Pixels per inch");

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPixelsPerInch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPixelsPerInch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPixelsPerInch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPixelsPerInch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabelSpeelduur.setText("Speelduur");

        javax.swing.GroupLayout jPanelSpeelduurLayout = new javax.swing.GroupLayout(jPanelSpeelduur);
        jPanelSpeelduur.setLayout(jPanelSpeelduurLayout);
        jPanelSpeelduurLayout.setHorizontalGroup(
            jPanelSpeelduurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpeelduurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSpeelduurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSpeelduur)
                    .addComponent(jTextFieldSpeelduur, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanelSpeelduurLayout.setVerticalGroup(
            jPanelSpeelduurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpeelduurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSpeelduur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSpeelduur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelNaamArtiest.setText("Naam artiest");

        jCheckBoxHeeftGenre.setText("Heeft genre");
        jCheckBoxHeeftGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHeeftGenreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMuziekLayout = new javax.swing.GroupLayout(jPanelMuziek);
        jPanelMuziek.setLayout(jPanelMuziekLayout);
        jPanelMuziekLayout.setHorizontalGroup(
            jPanelMuziekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuziekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMuziekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNaamArtiest, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNaamArtiest))
                .addGap(36, 36, 36)
                .addGroup(jPanelMuziekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxHeeftGenre)
                    .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanelMuziekLayout.setVerticalGroup(
            jPanelMuziekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuziekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMuziekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNaamArtiest)
                    .addComponent(jCheckBoxHeeftGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMuziekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNaamArtiest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButtonToevoegen.setText("Toevoegen");
        jButtonToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToevoegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonFoto)
                            .addComponent(jRadioButtonMuziek)
                            .addComponent(jRadioButtonFilm))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNaam)
                                    .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldGrootte, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSpeelduur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelMuziek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNaam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFoto)
                            .addComponent(jTextFieldNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFilm)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonMuziek))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jTextFieldGrootte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanelSpeelduur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanelMuziek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonToevoegen)
                .addGap(35, 35, 35))
        );

        jTabbedPane.addTab("Toevoegen", jPanel1);

        jScrollPane1.setViewportView(jListBestanden);

        jButtonSorteerOpNaam.setText("Standaard (sorteer op naam)");
        jButtonSorteerOpNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSorteerOpNaamActionPerformed(evt);
            }
        });

        jButtonSorteerOpGrootte.setText("Sorteer op compressiegrootte");
        jButtonSorteerOpGrootte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSorteerOpGrootteActionPerformed(evt);
            }
        });

        jButtonBewaringsdatum.setText("Sorteer op bewaringsdatum");
        jButtonBewaringsdatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBewaringsdatumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSorteerOpNaam)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonSorteerOpGrootte)
                        .addGap(168, 168, 168)
                        .addComponent(jButtonBewaringsdatum)
                        .addGap(0, 235, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSorteerOpNaam)
                    .addComponent(jButtonSorteerOpGrootte)
                    .addComponent(jButtonBewaringsdatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.addTab("Verzameling weergeven", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFotoActionPerformed
        setVisibility("foto");
    }//GEN-LAST:event_jRadioButtonFotoActionPerformed

    private void jRadioButtonFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFilmActionPerformed
        setVisibility("film");
    }//GEN-LAST:event_jRadioButtonFilmActionPerformed

    private void jRadioButtonMuziekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMuziekActionPerformed
        setVisibility("muziek");
    }//GEN-LAST:event_jRadioButtonMuziekActionPerformed

    private void jButtonToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToevoegenActionPerformed
        Bestand bestand;
        try {
            if (jRadioButtonFoto.isSelected()) {
                
                bestand = new Foto(jTextFieldNaam.getText(), Double.parseDouble(jTextFieldGrootte.getText()), Integer.parseInt(jTextFieldPixelsPerInch.getText()));
                
            } else if (jRadioButtonMuziek.isSelected()) {
                if(jCheckBoxHeeftGenre.isSelected())
                    bestand = new Muziek(jTextFieldNaam.getText(), Double.parseDouble(jTextFieldGrootte.getText()), Duration.ofMinutes(Integer.parseInt(jTextFieldSpeelduur.getText())), jTextFieldNaamArtiest.getText(), Genre.findGenreByBeschrijving(jComboBoxGenre.getSelectedItem().toString()));
                else
                    bestand = new Muziek(jTextFieldNaam.getText(), Double.parseDouble(jTextFieldGrootte.getText()), Duration.ofMinutes(Integer.parseInt(jTextFieldSpeelduur.getText())), jTextFieldNaamArtiest.getText());
            } else {
                bestand = new Film(jTextFieldNaam.getText(), Double.parseDouble(jTextFieldGrootte.getText()), Duration.ofMinutes(Integer.parseInt(jTextFieldSpeelduur.getText())));
            }
            collectie.addBestand(bestand);
            updateLijst();
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showConfirmDialog(this, "Geef een getal in", "Fout!", 2);
        }

    }//GEN-LAST:event_jButtonToevoegenActionPerformed

    private void jButtonSorteerOpNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSorteerOpNaamActionPerformed
        collectie.sort();
        updateLijst();
    }//GEN-LAST:event_jButtonSorteerOpNaamActionPerformed

    private void jButtonSorteerOpGrootteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSorteerOpGrootteActionPerformed
        collectie.sort(new SortByCompressieGrootte());
        updateLijst();
    }//GEN-LAST:event_jButtonSorteerOpGrootteActionPerformed

    private void jButtonBewaringsdatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBewaringsdatumActionPerformed
        collectie.sort(new SortByDatumBewaring());
        updateLijst();
    }//GEN-LAST:event_jButtonBewaringsdatumActionPerformed

    private void jCheckBoxHeeftGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHeeftGenreActionPerformed
        if (jCheckBoxHeeftGenre.isSelected()) {
            jComboBoxGenre.setVisible(true);
        } else {
            jComboBoxGenre.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxHeeftGenreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupBestandstype;
    private javax.swing.JButton jButtonBewaringsdatum;
    private javax.swing.JButton jButtonSorteerOpGrootte;
    private javax.swing.JButton jButtonSorteerOpNaam;
    private javax.swing.JButton jButtonToevoegen;
    private javax.swing.JCheckBox jCheckBoxHeeftGenre;
    private javax.swing.JComboBox<String> jComboBoxGenre;
    private javax.swing.JDialog jDialogMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNaam;
    private javax.swing.JLabel jLabelNaamArtiest;
    private javax.swing.JLabel jLabelPixelsPerInch;
    private javax.swing.JLabel jLabelSpeelduur;
    private javax.swing.JList<String> jListBestanden;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JPanel jPanelMuziek;
    private javax.swing.JPanel jPanelSpeelduur;
    private javax.swing.JRadioButton jRadioButtonFilm;
    private javax.swing.JRadioButton jRadioButtonFoto;
    private javax.swing.JRadioButton jRadioButtonMuziek;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldGrootte;
    private javax.swing.JTextField jTextFieldNaam;
    private javax.swing.JTextField jTextFieldNaamArtiest;
    private javax.swing.JTextField jTextFieldPixelsPerInch;
    private javax.swing.JTextField jTextFieldSpeelduur;
    // End of variables declaration//GEN-END:variables
}
